---
name: Issue with the Portalum ZVT Library
description: Report an issue with the zvt library (NuGet)
title: "**short summary**"
labels: ["question"]
body:

- type: markdown
  attributes:
    value: |
      Please fill in the information as completely as possible, if you can add the source code also helps to answer your question

- type: input
  id: nuget
  attributes:
    label: NuGet Package Version
    description: "What version of the NuGet package are you using"
    placeholder: "2.15.1"
  validations:
    required: false

- type: input
  id: paymentserviceprovider
  attributes:
    label: Payment service provider
    description: "Which payment service provider do you use"
    placeholder: "PAYONE / CardComplete / Hobex / ..."
  validations:
    required: true

- type: input
  id: paymentterminal
  attributes:
    label: Payment terminal
    description: "Which payment terminal do you use"
    placeholder: "ingenico iWL250"
  validations:
    required: true

- type: textarea
  id: communicationlogs
  attributes:
    label: Communication Logs
    description: "Please add log files from the communication"
  validations:
    required: false

- type: textarea
  id: information
  attributes:
    label: More information
    description: "You can enter more information here"
  validations:
    required: true